create table topic (
    id integer generated by default as identity primary key,
    name varchar(250) not null
);

CREATE TABLE offset_cache
(
    topicId integer not null,
    recordKey varchar(100),
    recordPartition smallint not null,
    recordOffset bigint not null,
    createdAt timestamp with time zone not null,
    foreign key (topicId) references topic(id)
);

create table last_cached_offset(
    topicId integer not null,
    partition smallint not null,
    lastOffset bigint not null,
    foreign key (topicId) references topic(id)
);

create index offset_cache_key on offset_cache(recordKey);
create index offset_cache_created_at on offset_cache(createdAt);
