---
apiVersion: data.nais.io/v1
kind: Postgres
metadata:
  name: kafka-offset-cache
  namespace: min-side
spec:
  cluster:
    majorVersion: "17"
    resources:
      cpu: 100m
      diskSize: 10Gi
      memory: 2G
  database:
    collation: nb_NO
---
apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tms-kafka-dashboard
  namespace: min-side
  labels:
    team: min-side
spec:
  image: {{version}}
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 15
  readiness:
    path: /internal/isReady
    initialDelay: 15
  prometheus:
    enabled: true
    path: /metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 20m
      memory: 128Mi
  azure:
    application:
      enabled: true
      tenant: nav.no
      claims:
        groups:
          - id: "cbe637e2-317f-48e1-a951-ce52fcea3fae"
    sidecar:
      enabled: true
      autoLogin: true
  ingresses:
    - https://tms-kafka-dashboard.intern.dev.nav.no
  kafka:
    pool: nav-dev
  postgres:
    clusterName: kafka-offset-cache
  env:
    - name: KAFKA_APP_CONFIG
      value: >
        {
          "topics": [
            {
              "topicName": "min-side.brukervarsel-v1"
            },
            {
              "topicName": "min-side.aapen-utkast-v1"
            },
            {
              "topicName": "min-side.aapen-varsel-hendelse-v1"
            },
            {
              "topicName": "min-side.aapen-microfrontend-v1"
            },
            {
              "topicName": "min-side.aapen-brukervarsel-v1"
            }
          ],
          "applications": []
        }
